services:
  vidflow-frontend:
    image: node:20-alpine
    working_dir: /app
    command: npm run dev
    volumes:
      - ./next-frontend:/app
    ports:
      - "4800:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:4880
    networks: [vidflow-network]

  vidflow-api:
    build:
      context: ./python-api
      dockerfile: Dockerfile.dev
    env_file: .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./python-api:/usr/src/app
      - ./media:/usr/src/app/media
    depends_on:
      - vidflow-redis
      - vidflow-db
    networks: [vidflow-network]

  vidflow-worker:
    build:
      context: ./go-worker
      dockerfile: Dockerfile.dev
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    volumes:
      - ./go-worker:/app
      - ./media:/app/media
    command: go run cmd/api/main.go
    depends_on:
      - vidflow-redis
      - vidflow-db
    networks: [vidflow-network]

  tyk-gateway:
    image: tykio/tyk-gateway:v5.2
    ports:
      - "4880:8080"
    volumes:
      - ./docker/tyk/tyk.conf:/opt/tyk-gateway/tyk.conf
      - ./docker/tyk/apps:/opt/tyk-gateway/apps
      - ./docker/tyk/policies:/opt/tyk-gateway/policies
      - ./docker/tyk/middleware:/opt/tyk-gateway/middleware
    depends_on:
      - vidflow-redis
    networks: [vidflow-network]

  vidflow-redis:
    image: redis:7-alpine
    ports:
      - "4809:6379"
    volumes:
      - redisdata:/data
    networks: [vidflow-network]

  vidflow-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vidflow
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks: [vidflow-network]

  vidflow-adminer:
    image: adminer:latest
    ports:
      - "4881:8080"
    depends_on:
      - vidflow-db
    networks: [vidflow-network]

volumes:
  db_data:
  redisdata:

networks:
  vidflow-network:
    driver: bridge