version: "3"
services:
  #PHP Service
  app:
    depends_on:
      - db
    image: lakhveerbawa/phpdock:arm821
    command:
      - php-fpm
    expose:
      - 9000:9000
      - 9003:9003
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network
    #Nginx Service

  job:
    depends_on:
      - db
    image: lakhveerbawa/phpdock:arm82
    entrypoint: /usr/bin/supervisord -n -c /etc/supervisord.conf
    expose:
      - 9000:9000
      - 13714:13714
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: job
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./docker/config/supervisor/conf.d:/etc/supervisor/conf.d
      - ./docker/job/supervisord.conf:/etc/supervisord.conf:delegated
    networks:
      - app-network
  #Nginx Service
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "2000:80"
      - "2001:443"
    volumes:
      - ./:/var/www
      - ./docker/config/nginx/conf.d.local/:/etc/nginx/conf.d/
      - ./docker/config/nginx/conf.d.local/ssl:/etc/nginx/ssl/
    networks:
      - app-network
  db:
    image: arm64v8/mysql
    restart: unless-stopped
    tty: true
    expose:
      - 3306
    ports:
      - "1303:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: DB_ROOT_PASS
      MYSQL_USER: lakhbawa
      MYSQL_PASSWORD: DB_ROOT_PASS
      TZ: UTC
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network
  redis:
    image: arm64v8/redis
    restart: unless-stopped
    tty: true
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    networks:
      - app-network
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: arm64v8/phpmyadmin
    restart: always
    ports:
      - '1083:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: DB_ROOT_PASS
      UPLOAD_LIMIT: 100M
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local

#  default:
#    external:
#      name: nginx-proxy
