FROM golang:1.25

WORKDIR /app

# Install system dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ffmpeg \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Copy go module files
COPY go.mod go.sum ./

RUN go mod download

# Copy the remaining source code
COPY . .

CMD ["go", "run", "main.go"]
