FROM golang:1.25-alpine

WORKDIR /app

# Install system dependencies (if needed for video processing)
RUN apk add --no-cache \
    ffmpeg \
    gcc \
    musl-dev

# Copy go module files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

CMD ["go", "run", "main.go"]